### ISSUE TITLE
I am getting error while opening file

### ISSUE THREAD

**Issue by timurproko** [sssooonnnggg/usdc-viewer#1]
I am getting this error
Command failed: usdcat "d:\Dropbox\Projects\_Houdini\out\lods_v1.usdc" -o "C:\Users\Timur\AppData\Local\Temp\lods_v1.usda" 'usdcat' is not recognized as an internal or external command, operable program or batch file.

What I am doing wrong, in VS Code setting I have this
"usdc-viewer.usdRoot": "D:\\Github\\OpenUSD\\",

I have put this repository 
https://github.com/PixarAnimationStudios/OpenUSD 
here
D:\Github\OpenUSD\

**Comment by sssooonnnggg** [comment]
You should use a prebuilt USD libraries instead of the USD source code, for example you can download from the Nvidia websites:
 https://developer.nvidia.com/usd#libraries-and-tools
 and then set usd root to it

**Comment by timurproko** [comment]
Thank you for clearing that up. I wasn't aware of the distinction between source and compiled. Once again, I appreciate your effort!
